"""initial baseline: PostGIS extension + core tables

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-04

This baseline materialises the four core tables (regions, weather_readings,
fire_events, satellite_tiles) from the ORM metadata, enabling the PostGIS
extension first. Subsequent schema changes are autogenerated with
``alembic revision --autogenerate``.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from sentinel.db import models  # noqa: F401  (populate metadata)
from sentinel.db.base import Base

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
